### PR TITLE
Version in tags triggers by Github tag

### PR DESCRIPTION
**Pull request by rdavid**

### CODE REVIEW

**Review by sebrandon1 — APPROVED** [review]

**Comment by rdavid** [comment]
@sebrandon1 In our case it is the same, in general Github releases and tags are not the same.

**Comment by sebrandon1** [comment]
Are you sure?  I think its referring to a git tag versus an image tag.

**Comment by sebrandon1** [comment]
Right but I don't think we are going to be manually pushing tags outside of a normal release?

**Comment by rdavid** [comment]
I think that you have to choose a tag in time you create a release. The tag is the version. The tag will trigger the action, the action will publish the image with the tag.

**Pull request merged**
