### PR TITLE
Rubocop Vagrantfile

### PR DESCRIPTION
**Pull request by rdavid**

### CODE REVIEW

**Review by sebrandon1 — APPROVED** [review]
What is rubocop?

**Comment by rdavid** [comment]
@sebrandon1 Vagrant is written in Ruby. Rubycop is Ruby static code analysis tool, linter. Take a look how the file is looked in my editor with linter before the PR:
Screen Shot 2022-08-15 at 18 00 42

**Comment by sebrandon1** [comment]
Ah "RUBYcop".  Cool!

**Comment by rdavid** [comment]
It is actually spelled similar to the movie Robocop:
 https://github.com/rubocop/rubocop

**Review by edcdavid — APPROVED** [review]

**Pull request merged**
