### PR TITLE
Update Kind to v0.17.0

### PR DESCRIPTION
**Pull request by sebrandon1**
https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0

### CODE REVIEW

**Comment by sebrandon1** [comment]
Seems to be failing because of something similar to: https://github.com/kubernetes-sigs/kind/issues/2880

Not exactly sure what the problem is.

**Comment by sebrandon1** [comment]
So somehow this branch works locally on my PC but fails in the CI.  I don't understand how/why it does the things it does right now.  🤣

**Comment by BenTheElder** [comment]
> EDIT: Seems like there's a problem with fedora36 and IPv6/docker/podman: https://github.com/containers/netavark/issues/439

podman switched to a whole new network backend in v4 and the distro packages can leave your networks in a broken state by being CNI networks but no longer shipping the CNI binaries.

I recommend
- ensure ipv6 is enabled (There typically isn't a reason not to) on the host
- ensure there is not a preexisting `kind` network, as it may be on the CNI mode which was broken in the package updates

**Review by edcdavid — APPROVED** [review]

**Comment by rdavid** [comment]
Cool!

**Pull request merged**
